# Generated by Django 3.0.3 on 2020-05-04 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClothModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('brandname', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('size', models.CharField(max_length=10)),
                ('style', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='cloth_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryModel',
            fields=[
                ('d_username', models.CharField(max_length=30)),
                ('d_password', models.CharField(max_length=20)),
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=50)),
                ('item_price', models.IntegerField()),
                ('item_image', models.ImageField(upload_to='')),
                ('cus_name', models.CharField(max_length=30)),
                ('cus_contact', models.IntegerField()),
                ('cus_adhar', models.IntegerField()),
                ('cus_addr', models.TextField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent2app.Login')),
            ],
        ),
    ]
