# Generated by Django 3.0.3 on 2020-05-05 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent2app', '0002_auto_20200505_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverymodel',
            name='item_name',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='deliverymodel',
            name='item_price',
            field=models.IntegerField(default=0),
        ),
    ]
