# Generated by Django 3.0.3 on 2020-05-05 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent2app', '0004_auto_20200505_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverymodel',
            name='d_password',
        ),
        migrations.RemoveField(
            model_name='deliverymodel',
            name='d_username',
        ),
    ]
